#Characters
define ron = Character("Ronald", image="ron")
define mar = Character("Marley", image="mar")
define dan = Character("Daniel")
define seb = Character("Sebastian")
define a = Character("Annabelle")
define c = Character("Chris")
define e = Character("Emily")
define san = Character("Sandra")
define n = Character("Norman")
define ter = Character("Terry")
define rob = Character("Robert")
define fra = Character("Franco")
define manny = Character("Manny")
define ben = Character("Benjamin")
define p = Character("Mrs Pear")
define der = Character("Derek")
define brent = Character("Brent")
define fre = Character("Freddy")
define w = Character("Wolf")
